export const SHOULD_UPDATE_YEAR:string='SHOULD_UPDATE_YEAR'
export const SHOULD_UPDATE_COURSE:string='UPDATE_COURSE'
export const SHOULD_UPDATE_SEMESTER:string='UPDATE_SEMESTER'
export const USER_DETAILS:string='USER_DETAILS'
