export const SELECT_YEAR="SELECT_YEAR"
export const SELECT_SEMESTER="SELECT_SEMESTER"
export const SELECT_COURSE="SELECT_COURSE"
export const SET_UNIT_NOTES='SET_UNIT_NOTES'
export const SET_SELECTED_UNIT_NOTES='SET_SELECTED_UNIT_NOTES'

